

nav:
  - index.md
  
  - Getting Started: getting-started.md
  
  - Environment:
    - environment/index.md
    
  - Live data:
    - live/get-lcls-live.md
    
  - Bmad: bmad/index.md
  
  - Developer: 
    - developer/index.md
    - Procedures: developer/procedures.md
    - Requirements: developer/requirements.md
    - mkdocs: developer/mkdocs.md
    - Roadmap: developer/roadmap.md      
  
  - Examples:
    - examples/archiver_example.ipynb
  
  - other/index.md
  
  - Help: help.md
  
  
site_name: LCLS-Live

theme:
  name: 'material'
  custom_dir: overrides
  
  
markdown_extensions:
  - codehilite  

  
plugins:
  - search
  - minify
  - mkdocs-jupyter:
      include_source: True